-libraryjars C:\JBuilderX\WTK23\lib\mmapi.jar;C:\JBuilderX\WTK23\lib\midpapi20.jar;C:\JBuilderX\WTK23\lib\wma11.jar;C:\JBuilderX\WTK23\lib\cldcapi10.jar
-injars C:\JBuilderX\WTK23\apps\SXMobileTuner\bin\SXMobileTuner.jar
-outjar C:\DOCUME~1\SarXos\USTAWI~1\Temp\SXMobileTuner.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
